In [1]:
import pandas as pd

l = [x*2 for x in range(5)]

s = pd.Series(l)

In [2]:
# Access by numeric index
print(s[2])

4

In [3]:
# Custom string indices
s = pd.Series(l, index=['p','q','r','s','t'])

print(s['t'])

8

In [4]:
# Duplicate indices
s = pd.Series(l, index=['x','y','z','z','y'])
print(s)

print(s['z'])

x    0
y    2
z    4
z    6
y    8
dtype: int64
z    4
z    6
dtype: int64

In [5]:
# Dictionary with changed values
data = {'x': 10, 'y': 20, 'z': 30, 'w': 40}

# Create Series directly from dictionary
s = pd.Series(data)
print(s)

x    10
y    20
z    30
w    40
dtype: int64

In [6]:
# Restrict Series to specific keys
s = pd.Series(data, index=['x','y'])
print(s)

x    10
y    20
dtype: int64

In [7]:
# Include an index not present in dictionary
s = pd.Series(data, index=['x','y','z','q'])
print(s)

x    10.0
y    20.0
z    30.0
q     NaN
dtype: float64

In [8]:
# Create a small DataFrame (changed values)
df = pd.DataFrame({
    'Name': ['Aarav', 'Meera', 'Kunal', 'Priya', 'Rohan'],
    'Age': [22, 27, 35, 19, 40],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male']
})

print(df.head())

    Name  Age  Gender
0  Aarav   22    Male
1  Meera   27  Female
2  Kunal   35    Male
3  Priya   19  Female
4  Rohan   40    Male

In [9]:
# Write DataFrame to JSON file
df.to_json('New_File.json')

# Read JSON file back into DataFrame
df_json = pd.read_json('New_File.json')
print(df_json)

    Name  Age  Gender
0  Aarav   22    Male
1  Meera   27  Female
2  Kunal   35    Male
3  Priya   19  Female
4  Rohan   40    Male

In [11]:
data = {
    'Name': ['Nithin', 'Manoj', 'Shivashankar', 'Swathi', 'Pareekshith'],
    'Age': [24, 30, 44, 18, 28],
    'Gender': ['Male', 'Male', 'Male', 'Female', 'Male']
}

df = pd.DataFrame(data)
df

           Name  Age  Gender
0        Nithin   24    Male
1         Manoj   30    Male
2  Shivashankar   44    Male
3        Swathi   18  Female
4   Pareekshith   28    Male

In [12]:
df.to_csv('SampleFilegzip.gz', compression='gzip', index=False)

In [14]:
df = pd.read_csv('SampleFilegzip.gz')
df

           Name  Age  Gender
0        Nithin   24    Male
1         Manoj   30    Male
2  Shivashankar   44    Male
3        Swathi   18  Female
4   Pareekshith   28    Male